using System;
using System.Collections.Generic;

namespace SCUMMRevLib.Decompilers.SCUMM
{
    public class SCUMMLineBuilder
    {
        private Dictionary<SCUMMOpcode, string> opcodeFormats = new Dictionary<SCUMMOpcode, string>
        {
            {SCUMMOpcode.C_ActorStuff,          "actor-stuff {0} {1}"                           },
            {SCUMMOpcode.C_Add,                 "{0} += {1}"                                    },
            {SCUMMOpcode.C_LAnd,                "{0} &= {1}"                                    },
            {SCUMMOpcode.C_StoreVariable,       "{0} is {1}"                                    },
            {SCUMMOpcode.C_StoreExpression,     "{0} is {1}"                                    },
            {SCUMMOpcode.C_AssignArray,         "{0} is {1}"                                    },
            {SCUMMOpcode.C_BreakHere,           "break-here"                                    }, // Overloaded
            {SCUMMOpcode.C_CameraAt,            "camera-at {0}"                                 },
            {SCUMMOpcode.C_CameraFollow,        "camera-follow {0}"                             },
			{SCUMMOpcode.C_CameraInRoom,        "current-room {0}"                              },
			{SCUMMOpcode.C_CameraPanTo,         "camera-pan-to {0}"                             },
			{SCUMMOpcode.C_ChainScript,         "chain-script {0} {1}"                          },
			{SCUMMOpcode.C_ComeOutDoor,         "come-out-door {0} in-room {1}"                 },
			{SCUMMOpcode.C_CutScene,            "cut-scene {0} {{"                              },
			{SCUMMOpcode.C_Debug,               "debug {0}"                                     },
			{SCUMMOpcode.C_DecVariable,         "--{0}"                                         },
			{SCUMMOpcode.C_Div,                 "{0} /= {1}"                                    },
			{SCUMMOpcode.C_DoAnimation,         "do-animation {0} {1}"                          }, // stop-actor = do-animation <actor> 0xff
			{SCUMMOpcode.C_DoSentence,          "do-sentence {0} {1} with {2}"                  },
            {SCUMMOpcode.C_DrawBox,             "draw-box {0},{1} to {2},{3} color {4}"         },
            {SCUMMOpcode.C_DrawObject,          "draw-object {0}"                               },
            {SCUMMOpcode.C_DrawObjectAt,        "draw-object {0} at {1},{2}"                    },
            {SCUMMOpcode.C_DrawObjectImage,     "draw-object {0} image {1}"                     },
			{SCUMMOpcode.C_EndCutScene,         "}} ; end cut-scene"                            },
            {SCUMMOpcode.C_EndObject,           "}} ; end object"                               },
			{SCUMMOpcode.C_EndScript,           "}} ; end script"                               },
			{SCUMMOpcode.C_FaceTowards,         "do-animation {0} face-towards {1}"             },
			{SCUMMOpcode.C_FreezeScripts,       "freeze-scripts"                                }, // no parameter = 0x7f
			{SCUMMOpcode.C_HeapStuff,           "HEAP-STUFF {0} ; FIXME"                        },
			{SCUMMOpcode.C_IfClassOf,           "if (class-of {0} is {1}) jump {2}"             },
			{SCUMMOpcode.C_IfEq,                "if ({0} = {1}) jump {2}"                       },
			{SCUMMOpcode.C_IfGeq,               "if ({0} >= {1}) jump {2}"                      },
			{SCUMMOpcode.C_IfGt,                "if ({0} > {1}) jump {2}"                       },
			{SCUMMOpcode.C_IfInBox,             "if ({0} is in-box {1}) jump {2}"               },
			{SCUMMOpcode.C_IfLeq,               "if ({0} <= {1}) jump {2}"                      },
			{SCUMMOpcode.C_IfLt,                "if ({0} < {1}) jump {2}"                       },
			{SCUMMOpcode.C_IfNeq,               "if ({0} != {1}) jump {2}"                      },
			{SCUMMOpcode.C_IfNotVar,            "if (!{0}) jump {1}"                            },
			{SCUMMOpcode.C_IfVar,               "if ({0}) jump {1}"                             },
			{SCUMMOpcode.C_IncVariable,         "++{0}"                                         },
			{SCUMMOpcode.C_Jump,                "jump {0}"                                      },
			{SCUMMOpcode.C_Lights,              "lights"                                        },
			{SCUMMOpcode.C_Mul,                 "{0} *= {1}"                                    },
			{SCUMMOpcode.C_NewNameOf,           "new-name-of {0} is {1}"                        },
			{SCUMMOpcode.C_NewVerb,             "new-verb {0} {1}"                              },
			{SCUMMOpcode.C_LOr,                 "{0} |= {1}"                                    },
			{SCUMMOpcode.C_Override,            "override {0}"                                  },
			{SCUMMOpcode.C_OwnerOf,             "owner-of {0} is {1}"                           },
			{SCUMMOpcode.C_PickUpObjectInRoom,        "pick-up-object {0} in-room {1}"                },
			{SCUMMOpcode.C_PickUpObject,  "pick-up-object {0}"                            },
			{SCUMMOpcode.C_Pseudoroom,          "pseudoroom {0} is {1}"                         },
			{SCUMMOpcode.C_PutActorAtXY,        "put-actor {0} at {1}, {2}"                     },
			{SCUMMOpcode.C_PutActorAtObject,    "put-actor {0} at-object {1}"                   },
			{SCUMMOpcode.C_PutActorInRoom,      "put-actor {0} in-room {1}"                     },
			{SCUMMOpcode.C_RoomStuff,           "ROOM-STUFF {0} ; FIXME"                        },
			//{SCUMMOpcode.C_SaveLoadVariables,                                                   },
			{SCUMMOpcode.C_SayLine,             "say-line {0} {1}"                              },
			{SCUMMOpcode.C_SayLineDefault,      "say-line {0}"                                  },
            {SCUMMOpcode.C_SetBox,              "SET-BOX {0} ; FIXME"                           },
            {SCUMMOpcode.C_ClassOf,             "class-of {0} is {1}"                           },
            {SCUMMOpcode.C_StateOf,             "state-of {0} is {1}"                           },
            {SCUMMOpcode.C_SleepJiffies,        "sleep-for {0} jiffies"                         },
            {SCUMMOpcode.C_SleepForVar,         "sleep-for {0} jiffies"                         },
            //{SCUMMOpcode.C_SoundKludge,                                                         },
            {SCUMMOpcode.C_StartMusic,          "start-music {0}"                               },
            {SCUMMOpcode.C_StartObject,         "start-object {0} {1}"                          }, // Overloaded?
            {SCUMMOpcode.C_StartScript,         "start-script {0} {1}"                          }, // Options are stored in opcode byte
            {SCUMMOpcode.C_StartSound,          "start-sound {0}"                               },
            {SCUMMOpcode.C_StopMusic,           "stop-music"                                    },
            {SCUMMOpcode.C_StopObject,          "stop-object {0}"                               },
            {SCUMMOpcode.C_StopScriptDefault,   "stop-script"                                   }, // parameter = 0
            {SCUMMOpcode.C_StopSound,           "stop-sound {0}"                                },
            {SCUMMOpcode.C_StringStuff,         "STRING-STUFF {0} ; FIXME"                      },
            {SCUMMOpcode.C_Sub,                 "{0} -= {1}"                                    },
            {SCUMMOpcode.C_System,              "SYSTEM {0} ; FIXME"                            },
            {SCUMMOpcode.C_Unknown,             "UNKNOWN! ; FIXME - opcode {0}"                 },
            {SCUMMOpcode.C_Userface,            "USERFACE {0} ; FIXME"                          },
            {SCUMMOpcode.C_VerbSets,            "VERBSETS {0} ; FIXME"                          },
            {SCUMMOpcode.C_WaitForStuff,        "WAIT-FOR-STUFF {0} ; FIXME"                    },
            {SCUMMOpcode.SC_WaitForActor,       "wait-for-actor {0}"                            },
            {SCUMMOpcode.SC_WaitForMessage,     "wait-for-message"                              },
            {SCUMMOpcode.SC_WaitForCamera,      "wait-for-camera"                               },
            {SCUMMOpcode.SC_WaitForSentence,    "wait-for-sentence"                             },
            {SCUMMOpcode.C_WalkToXY,            "walk {0} to {1},{2}"                           },
            {SCUMMOpcode.C_WalkToActor,         "walk {0} to-actor {1}"                         },
            {SCUMMOpcode.C_WalkToActorWithin,   "walk {0} to-actor {1} within {2}"              },
            {SCUMMOpcode.C_WalkToObject,        "walk {0} to-object {1}"                        },
            {SCUMMOpcode.F_ActorBox,            "{0} = actor-box({1})"                          }, 
            {SCUMMOpcode.F_ActorCostume,        "{0} = actor-costume({1})"                      }, 
            {SCUMMOpcode.F_ActorElevation,      "{0} = actor-elevation({1})"                    }, 
            {SCUMMOpcode.F_ActorFacing,         "{0} = actor-facing({1})"                       },
            {SCUMMOpcode.F_ActorMoving,         "{0} = actor-moving({1})"                       },
            {SCUMMOpcode.F_ActorRoom,           "{0} = actor-room({1})"                         },
            {SCUMMOpcode.F_ActorScale,          "{0} = actor-scale({1})"                        },
            {SCUMMOpcode.F_ActorWidth,          "{0} = actor-width({1})"                        },
            {SCUMMOpcode.F_ActorX,              "{0} = actor-x({1})"                            },
            {SCUMMOpcode.F_ActorY,              "{0} = actor-y({1})"                            },
            {SCUMMOpcode.F_AnimationCounter,    "{0} = animation-counter({1})"                  },
            {SCUMMOpcode.F_ClosestActor,        "{0} = closest-actor({1})"                      },
            {SCUMMOpcode.F_FindActor,           "{0} = find-actor({1}, {2})"                    },
            {SCUMMOpcode.F_FindInventory,       "{0} = find-inventory({1}, {2})"                },
            {SCUMMOpcode.F_FindObject,          "{0} = find-object({1}, {2})"                   },
            {SCUMMOpcode.F_InventorySize,       "{0} = inventory-size({1})"                     },
            {SCUMMOpcode.F_OwnerOf,             "{0} = owner-of {1}"                            },
            {SCUMMOpcode.F_Proximity2ActObjs,   "{0} = proximity({1}, {2})"                     },
            {SCUMMOpcode.F_Random,              "{0} = random({1})"                             },
            {SCUMMOpcode.F_ScriptRunning,       "{0} = script-running({1})"                     },
            {SCUMMOpcode.F_SoundRunning,        "{0} = sound-running({1})"                      },
            {SCUMMOpcode.F_StateOf,             "{0} = state-of {1}"                            },
            {SCUMMOpcode.F_StringWidth,         "{0} = width {1}"                               },
            {SCUMMOpcode.F_ValidVerb,           "{0} = valid-verb({1}, {2})"                    },
                                                                                                
            {SCUMMOpcode.SC_CursorOn,           "cursor on"                                     },
            {SCUMMOpcode.SC_CursorOff,          "cursor off"                                    },
            {SCUMMOpcode.SC_UserputOn,          "userput on"                                    },
            {SCUMMOpcode.SC_UserputOff,         "userput off"                                   },
            {SCUMMOpcode.SC_CursorSoftOn,       "cursor soft-on"                                },
            {SCUMMOpcode.SC_CursorSoftOff,      "cursor soft-off"                               },
            {SCUMMOpcode.SC_UserputSoftOn,      "userput soft-on"                               },
            {SCUMMOpcode.SC_UserputSoftOff,     "userput soft-off"                              },
            {SCUMMOpcode.SC_UserputClear,       "userput clear"                                 },
            {SCUMMOpcode.SC_CursorImage_3,      "cursor {0} image {1}"                          },
            {SCUMMOpcode.SC_CursorHotspot,      "cursor {0} hotspot {1},{2}"                    },
            {SCUMMOpcode.SC_CursorSet,          "cursor {0}"                                    },
            {SCUMMOpcode.SC_CharsetSet,         "charset {0}"                                   },
            {SCUMMOpcode.SC_CharsetColor,       "charset-color {0}"                             },
                                                                                                
            {SCUMMOpcode.SC_HeapLoadScript,     "load-script {0}"                               },
            {SCUMMOpcode.SC_HeapLoadSound,      "load-sound {0}"                                },
            {SCUMMOpcode.SC_HeapLoadCostume,    "load-costume {0}"                              },
            {SCUMMOpcode.SC_HeapLoadRoom,       "load-room {0}"                                 },
            {SCUMMOpcode.SC_HeapNukeScript,     "nuke-script {0}"                               },
            {SCUMMOpcode.SC_HeapNukeSound,      "nuke-sound {0}"                                },
            {SCUMMOpcode.SC_HeapNukeCostume,    "nuke-costume {0}"                              },
            {SCUMMOpcode.SC_HeapNukeRoom,       "nuke-room {0}"                                 },
            {SCUMMOpcode.SC_HeapLockScript,     "lock-script {0}"                               },
            {SCUMMOpcode.SC_HeapLockSound,      "lock-sound {0}"                                },
            {SCUMMOpcode.SC_HeapLockCostume,    "lock-costume {0}"                              },
            {SCUMMOpcode.SC_HeapLockRoom,       "lock-room {0}"                                 },
            {SCUMMOpcode.SC_HeapUnlockScript,   "unlock-script {0}"                             },
            {SCUMMOpcode.SC_HeapUnlockSound,    "unlock-sound {0}"                              },
            {SCUMMOpcode.SC_HeapUnlockCostume,  "unlock-costume {0}"                            },
            {SCUMMOpcode.SC_HeapUnlockRoom,     "unlock-room {0}"                               },
            {SCUMMOpcode.SC_HeapClearHeap,      "clear-heap"                                    },
            {SCUMMOpcode.SC_HeapLoadCharset,    "load-charset {0}"                              },
            {SCUMMOpcode.SC_HeapNukeCharset,    "nuke-charset {0}"                              },
            {SCUMMOpcode.SC_HeapLoadObject,     "load-object {0} {1}"                           },

            {SCUMMOpcode.SC_SystemRestart,      "restart"                                       },
            {SCUMMOpcode.SC_SystemPause,        "pause"                                         },
            {SCUMMOpcode.SC_SystemQuit,         "quit"                                          },
                                                                                                
            {SCUMMOpcode.SC_SetBoxSpecial,      "set-box {0} {1}"                               },
            {SCUMMOpcode.SC_SetBoxScale,        "set-box {0} scale {1}"                         },
            {SCUMMOpcode.SC_SetBoxSlot,         "set-box {0} slot {1}"                          },
            {SCUMMOpcode.SC_SetBoxPath,         "set-box path"                                  },
                                                                                                
            {SCUMMOpcode.SC_RoomScroll,         "room-scroll is {0} {1}"                        },
            {SCUMMOpcode.SC_RoomColor,          "room-color is {0} in-slot {1}"                 },
            {SCUMMOpcode.SC_RoomSetScreen,      "set-screen {0} to {1}"                         },
            {SCUMMOpcode.SC_RoomPalette,        "palette {0} in-slot {1}"                       },
            {SCUMMOpcode.SC_RoomShakeOn,        "shake off"                                     },
            {SCUMMOpcode.SC_RoomShakeOff,       "shake on"                                      },
            {SCUMMOpcode.SC_RoomScale,          "room-scale {0} at {1} {2} at {3} in-slot {4}"  },
            {SCUMMOpcode.SC_RoomIntensity,      "palette intensity {0} in-slot {1} to {2}"      },
            {SCUMMOpcode.SC_RoomSaveLoadGame,   "saveload-game {0} in-slot {1}"                 },
            {SCUMMOpcode.SC_RoomFade,           "fades {0}"                                     },
            {SCUMMOpcode.SC_RoomRgbIntensity,   "palette intensity {0},{1},{2} in-slot {3} to {4}"},
            //{SCUMMOpcode.C_RoomShadow,                                                          },
            //{SCUMMOpcode.C_SaveString,                                                          },
            //{SCUMMOpcode.C_LoadString,                                                          },
            {SCUMMOpcode.SC_RoomTransform,      "palette transform {0} in-slot {1} to {2} steps {3}"},
            {SCUMMOpcode.SC_RoomCycleSpeed,     "palette cycle-speed {0} is {1}"                  },
                                                                                                
            {SCUMMOpcode.C_StringIsStrval,      "*{0} = {1}"                                    },
            {SCUMMOpcode.C_StringIsStrvar,      "*{0} = *{1}"                                   },
            {SCUMMOpcode.C_StringIsVal,         "*{0}[{1}] = {2}"                               },
            {SCUMMOpcode.C_VarIsString,         "{0} = *{1}[{2}]"                               },
            {SCUMMOpcode.C_DimString,           "*{0}[{1}]"                                     },

            {SCUMMOpcode.SC_VerbsSave,           "save-verbs {0} {1} {2}"                       },
            {SCUMMOpcode.SC_VerbsRestore,        "restore-verbs {0} {1} {2}"                    },
            {SCUMMOpcode.SC_VerbsDelete,         "delete-verbs {0} {1} {2}"                     },

            {SCUMMOpcode.C_FreezeScript,        "freeze-script {0}"                             },
            {SCUMMOpcode.C_StopSentence,        "stop-sentence {0}"                             },
            {SCUMMOpcode.C_UnfreezeScripts,     "unfreeze-scripts"                              }, // parameter = 0
            {SCUMMOpcode.C_StopScript,          "stop-script {0}"                               },
            {SCUMMOpcode.C_BreakHereCount,      "break-here {0}"                                },
            {SCUMMOpcode.C_OverrideOff,         "override off"                                  },
            {SCUMMOpcode.C_StartScriptBak,      "start-script bak {0} {1}"                      },
            {SCUMMOpcode.C_StartScriptRec,      "start-script rec {0} {1}"                      },
            {SCUMMOpcode.C_StartScriptBakRec,   "start-script bak rec {0} {1}"                  },
            {SCUMMOpcode.C_SleepSeconds,     "sleep-for {0} seconds"                            },
            {SCUMMOpcode.C_SleepMinutes,     "sleep-for {0} minutes"                            },
            {SCUMMOpcode.C_PrintLine,           "print-line {0}"                                },
            {SCUMMOpcode.C_PrintText,           "print-text {0}"                                },
            {SCUMMOpcode.C_PrintDebug,          "print-text {0}"                                },
            {SCUMMOpcode.C_PrintSystem,         "print-system {0}"                              },

            {SCUMMOpcode.I_FlushSoundQueue,          "flush-sound-q"                            },
            {SCUMMOpcode.I_GetPlayStatus,            "sound-play-status {1}"                    },
            {SCUMMOpcode.I_StopAllSounds,            "stop-all-sounds"                          },
            {SCUMMOpcode.I_MIDI_ClearCommandQueue,   "clear-command-q"                          },
            {SCUMMOpcode.I_MIDI_EnqueueTrigger,      "q-sound-trigger {1} {2}"                  },
            //{SCUMMOpcode.I_MIDI_EnqueueCommand,      "q-sound-command {1} {2}"                         },
        };

        public string GetLine(SCUMMCommand cmd)
        {
            if (opcodeFormats.ContainsKey(cmd.Opcode))
            {
                return String.Format(opcodeFormats[cmd.Opcode], cmd.Parameters);
            }

            return cmd.ToString();
        }
    }
}
