using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SCUMMRevLib.Chunks
{
    public enum ImageIndex : int
    {
        None = 0,
        ThreeD,
        AnimationInfo,
        Max,
        Amiga,
        Box,
        BoxMatrix,
        Bundle,
        ScriptInfo,
        CharacterSet,
        CompressionTable,
        CostumeInfo,
        Costume,
        Cycle,
        DirectoryCharacters,
        DirectoryCostumes,
        Dialogue,
        DigitalSound,
        DirectoryObjects,
        DirectoryRooms,
        DirectoryScripts,
        DirectorySounds,
        RoomEntry,
        RoomExit,
        Globals,
        AnimationSound,
        Image,
        ImageInfo,
        IMuse,
        Keyframe,
        Map,
        Material,
        Midi,
        Movie,
        ObjectImage,
        Palette,
        RoomInfo,
        RoomImageInfo,
        RoomImage,
        Room,
        Save,
        Scale,
        Script,
        Pixelmap,
        Lips,
        Table,
        Text,
        Transparency,
        Unknown,
        Used,
        Vars,
        Verb,
        Wave,
        ZBuffer,
        FolderImages,
        FolderKeys,
        FolderMovies,
        FolderPalettes,
        FolderScripts,
        FolderScumm,
        FolderSounds,
        Folder

    }
}
